### PR TITLE
increment version

### PR DESCRIPTION
**Pull request by yate**
I changed the About page so it gets the version name and build date programmatically, so there should be no need for version.xml anymore, the numbers will only be in the manifest.

I couldn't find any references to ChanApps LLC so I didn't change anything there.

### CODE REVIEW

**Comment by yate** [comment]
So once there is a release made for 2.0.4 on github, I think f-droid will automatically bring in the update?  I'm not sure how it works.

**Comment by johnarleyburns** [comment]
Yeah im not sure.

**Comment by yate** [comment]
It looks like as long as you create a new release and put in the tag version (v2.0.4), F-Droid will pick it up.

**Comment by johnarleyburns** [comment]
I'm still seeing the old 2.0.3 version on f-droid, do we have to notify
someone to update the version?

**Comment by yate** [comment]
The latest release on github is still 2.0.3 https://github.com/grzegorznittner/chanu/releases.  Not sure if it's a nightly job or happens immediately, but we shouldn't need to contact anyone.

**Comment by yate** [comment]
In other words, you have to do this https://github.com/blog/1547-release-your-software

**Comment by johnarleyburns** [comment]
I think this is something greg has to do as he's the owner of the repo.

**Comment by grzegorznittner** [comment]
first git repo will have to be tagged, then we can draft new release,
actually any collaborator can do that

**Comment by grzegorznittner** [comment]
i think that the tag name is important, as it is used as release version
please try it, if it won't work for you i'll have a look on it tomorrow

**Comment by yate** [comment]
Creating a release also makes a tag.

**Comment by johnarleyburns** [comment]
Okay I've created a new release, don't know if this will work on f-droid,
I'm not sure how long is needed to wait.

**Comment by yate** [comment]
Looks like the Travis deploy job worked :)

**Comment by johnarleyburns** [comment]
f-droid is still 2.0.3 though...

https://f-droid.org/repository/browse/?fdfilter=chanu&fdid=com.chanapps.four.activity

**Comment by johnarleyburns** [comment]
There must be something we're doing wrong, f-droid isn't picking up the new
version.

**Comment by yate** [comment]
Looks like it runs nightly.  We should see it tonight. https://f-droid.org/wiki/page/FAQ_-_App_Developers#I.27ve_published_a_new_release._Why_is_it_not_in_the_repository.3F

**Comment by johnarleyburns** [comment]
does this have the lolipop fix?

**Comment by yate** [comment]
It has the fix for the crash on start up in lollipop, but I didn't test much else of the app.

**Comment by johnarleyburns** [comment]
good, we have some loli volunteers

**Comment by yate** [comment]
They updated the metadata  https://gitlab.com/fdroid/fdroiddata/commit/abd2ba5bb1bdd0d84671e1d65336c0f580f9940e so it should be reflected soon

**Comment by johnarleyburns** [comment]
Okay will this make it update?  I'm still seeing 2.0.3:

https://f-droid.org/repository/browse/?fdfilter=chanu&fdid=com.chanapps.four.activity

**Comment by yate** [comment]
Yeah it will, it's in the apps to update page https://f-droid.org/wiki/page/Category:Apps_to_Update.  According to the wiki:"As long as the text under Versions stating "The current (recommended) version is xxx (version code yyy)" shows the version numbers corresponding to your latest release, we detected it and the APK should be available soon. Just give it some time."

**Pull request merged**
