### PR TITLE
don't repeat words since a one word captcha is now possible

### PR DESCRIPTION
**Pull request by yate**

### CODE REVIEW

**Comment by yate** [comment]
Any luck getting it working? It's been working for me each time now.

**Comment by johnarleyburns** [comment]
Yes I've submitted 2.0.8 to f-droid as well.

**Comment by johnarleyburns** [comment]
Upped it to 2.0.9, but i don't see it on their apps to update for some
reason.

**Comment by yate** [comment]
I don't know it usually happens overnight to detect the update, then a day or two to actually update the app.  If it doesnt go in tonight I can ask them tomorrow

**Comment by johnarleyburns** [comment]
its up now and working great!

**Pull request merged**
