### PR TITLE
implement recaptcha-v2 for easier captchas

### PR DESCRIPTION
**Pull request by yate**
Recaptcha v2 thanks to https://github.com/Floens/Clover/issues/58

Let me know if you have any issues running this.  Reporting captcha is not implemented yet.

### CODE REVIEW

**Comment by johnarleyburns** [comment]
Do you think this is ready for release?

**Comment by yate** [comment]
I would say yes... i.e. works on my device :smile:

**Comment by johnarleyburns** [comment]
okay ill test too

**Comment by johnarleyburns** [comment]
Created new release 2.0.13, should be up on fdroid in a few days.

What do you think if we re-pushed the GPL'd app to google play?  We should
probably switch to the official 4chan logo just to be safe instead of the
one I used which the Bank of America seemed to not like.

**Comment by yate** [comment]
Was it really Bank of America lol?  Changing the logo sounds good, although the 4chan API says `You may not use the 4chan name, logo, or brand to promote your application, product, or service.` so we'll probably have to create something else.

**Comment by johnarleyburns** [comment]
Yeah, any ideas?  They might not care since it's GPLd.

**Comment by Azebu** [comment]
Maybe just slap U in the corner of logo? 
Moot is gone anyway, who's going to pursue you for it.

**Comment by johnarleyburns** [comment]
Sure, if someone can do an inkscape I'll generate all the android assets
and throw it up there.  I have a non-profit called Free Apps Foundation, I
can register it under that.

**Comment by yate** [comment]
Any of [these](http://i.imgur.com/DD2GGTC.png) pan out? Or too similar to the original?

**Comment by johnarleyburns** [comment]
They are close but we'd want to drop the shadow at least to keep with more
material-style design.

**Pull request merged**
