### PR TITLE
fix bug where rotating the screen in a thread will take you back to the ...

### PR DESCRIPTION
**Pull request by yate**
...board page

For some reason screen rotation was causing the switchBoard method to be called in ThreadActivity, which starts a new BoardActivity.  I couldn't figure out why it is calling that but the simple fix is to check if the board you're switching to is already your current board, then no action is required.

There was also an issue when if you rotated the screen on a thread, then picked a new board, the board would not load.  I had to modify the if in BoardActivity in order for it to refresh properly, i'm not sure of the consequences of that.

I also removed some of the finish() calls, I don't know if they're necessary or not but it seems to work without it, and android will end up killing the activity right?

### CODE REVIEW

**Comment by johnarleyburns** [comment]
this seems okay, i think we just test it some for awhile and see how it
works.  a lot of the code around boards is convoluted unfortunately

**Comment by yate** [comment]
Did you get a chance to test this one yet?  Its been working okay for me so far.

**Comment by yate** [comment]
FYI this will fix the issue that Javier Ruiz is talking about in [this thread](https://plus.google.com/103528179847058661880/posts/9PTsKtYeabf).  I can take a closer look and try to figure out why the event is being called in the first place, if that would be worthwhile.

**Comment by johnarleyburns** [comment]
I tried to refactor at one point but ended up breaking other things.

**Comment by yate** [comment]
Do you want to merge for now and we can try to refactor later?

**Comment by johnarleyburns** [comment]
okay done, will be nice if it fixes it for everyone

**Comment by yate** [comment]
Cool I hope so.  What do you think about doing a release (if you don't run into any issues)?  It would include this and the memory fixes

**Comment by johnarleyburns** [comment]
Yes, but we need to up the android version number.  Also the publisher is
no longer ChanApps LLC but the nonprofit Free Apps Foundation, Inc. email
for support is john@faf.io.  Also we need to add you in the credits.

**Pull request merged**
