### PR TITLE
Memory leaks

### PR DESCRIPTION
**Pull request by yate**

### CODE REVIEW

**Comment by yate** [comment]
After browsing for 5-10 minutes images stop loading and my app crashes the next image I click on with an OutOfMemoryException.  This change should fix that.

**Comment by johnarleyburns** [comment]
okay i think we are ready to submit to fdroid

**Comment by yate** [comment]
I just read https://plus.google.com/+JohnArleyBurns/posts/4FWCnLyVhRr, did you mean to merge this?

**Comment by johnarleyburns** [comment]
Yes did I not merge it?  I thought it was merged.

**Comment by yate** [comment]
Looks good now :)

**Pull request merged**
